apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-crypto
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      username: default
      defaultDatabase: default
      protocol: http
    secureJsonData:
      password: ""
    editable: true
